### ISSUE TITLE
Lostash ruby filter throws undefined method strftime

### ISSUE THREAD

**Issue by 91pavan** [logstash-plugins/logstash-filter-ruby#4]
For some reason, ruby is throwing exception for this perfectly valid ruby filter code:

```
 ruby {
        code => "
year = (Time.now.year).to_s.force_encoding('UTF-8')
event['time'] = Time.parse(event['@timestamp'].strftime(year+'-%m-%d %H:%M:%S.%L') + ' UTC')
 "
    }
```

```
Exception in filterworker {"exception"=>#<NoMethodError: undefined method `strftime' for "2015-03-04T13:53:25.604Z":LogStash::Timestamp>, "backtrace"=>["(ruby filter code):3:in `register'", 
"org/jruby/RubyProc.java:271:in `call'", "/home/vagrant/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-0.1.4/lib/logstash/filters/ruby.rb:37:in `filter'", "(eval):3009:in `initialize'", 
"org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):3005:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", 
"org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):2927:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/home/vagrant/logstash/lib/logstash/pipeline.rb:275:in `filter'", "/home/vagrant/logstash/lib/logstash/pipeline.rb:209:in `filterworker'", 
"/home/vagrant/logstash/lib/logstash/pipeline.rb:153:in `start_filters'"], :level=>:error}
```

It works just fine in 1.4.2

**Comment by netoneko** [comment]
```
init => "require 'time'"
```

**Comment by jsvd** [comment]
In 1.5 `@timestamp` is now an instance of LogStash::Timestamp instead of Time. While the former wraps around the latter, it doesn't expose all methods of a Time instance, and that's why it's not working.

I'll create a PR to expose strftime. In the meatime you have to do `event['@timestamp'].time.strftime('...')`

**Comment by jsvd** [comment]
Solution here: https://github.com/elastic/logstash/issues/2762#issuecomment-98833843
