### ISSUE TITLE
Lostash ruby filter throws undefined method strftime

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-ruby#9]
(This issue was originally filed by @91pavan at https://github.com/elastic/logstash/issues/2762)

---

For some reason, ruby is throwing exception for this perfectly valid ruby filter code:

```
 ruby {
        code => "
year = (Time.now.year).to_s.force_encoding('UTF-8')
event['time'] = Time.parse(event['@timestamp'].strftime(year+'-%m-%d %H:%M:%S.%L') + ' UTC')
 "
    }
```

```
Exception in filterworker {"exception"=>#<NoMethodError: undefined method `strftime' for "2015-03-04T13:53:25.604Z":LogStash::Timestamp>, "backtrace"=>["(ruby filter code):3:in `register'", 
"org/jruby/RubyProc.java:271:in `call'", "/home/vagrant/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-0.1.4/lib/logstash/filters/ruby.rb:37:in `filter'", "(eval):3009:in `initialize'", 
"org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):3005:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", 
"org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):2927:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/home/vagrant/logstash/lib/logstash/pipeline.rb:275:in `filter'", "/home/vagrant/logstash/lib/logstash/pipeline.rb:209:in `filterworker'", 
"/home/vagrant/logstash/lib/logstash/pipeline.rb:153:in `start_filters'"], :level=>:error}
```

It works just fine in 1.4.2

**Comment by iphone4plus** [comment]
filter {
   ruby {
      #code => "event['@timestamp'] = event['@timestamp'].local('+08:00')"
      code => "event['@timestamp'] = event['@timestamp'].localtime('+08:00')"
      #code => "event['@timestamp'] = event['@timestamp'].getlocal"
   }
}

error infomation:
Ruby exception occurred: undefined method `localtime' for "2015-08-28T05:43:17.530Z":LogStash::Timestamp {:level=>:error}

**Comment by infinityhacks** [comment]
same error here. Is there any plan to fix this ?
